-- VOTE database
-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  created_at timestamptz default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  created_at timestamptz default now(),
  constraint one_vote_per_user unique (user_id)
);

create table if not exists public.vote_settings (
  id int primary key default 1 check (id = 1),
  title text not null default '투표',
  description text default 'Google 계정으로 로그인한 뒤 한 사람당 한 번만 투표할 수 있습니다.',
  updated_at timestamptz default now()
);

insert into public.vote_settings (id, title, description)
values (1, '투표', 'Google 계정으로 로그인한 뒤 한 사람당 한 번만 투표할 수 있습니다.')
on conflict (id) do nothing;

alter table public.candidates enable row level security;
alter table public.votes enable row level security;
alter table public.vote_settings enable row level security;

drop policy if exists "Anyone can view candidates" on public.candidates;
create policy "Anyone can view candidates"
on public.candidates for select using (true);

drop policy if exists "Admins can insert candidates" on public.candidates;
create policy "Admins can insert candidates"
on public.candidates for insert to authenticated
with check (
  (auth.jwt() ->> 'email') = any (array['sj10225@dge.go.kr'])
);

drop policy if exists "Admins can update candidates" on public.candidates;
create policy "Admins can update candidates"
on public.candidates for update to authenticated
using ((auth.jwt() ->> 'email') = any (array['sj10225@dge.go.kr']))
with check ((auth.jwt() ->> 'email') = any (array['sj10225@dge.go.kr']));

drop policy if exists "Admins can delete candidates" on public.candidates;
create policy "Admins can delete candidates"
on public.candidates for delete to authenticated
using ((auth.jwt() ->> 'email') = any (array['sj10225@dge.go.kr']));

drop policy if exists "Users can view own vote" on public.votes;
create policy "Users can view own vote"
on public.votes for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "Anyone can view vote counts" on public.votes;
create policy "Anyone can view vote counts"
on public.votes for select using (true);

drop policy if exists "Users can vote once" on public.votes;
create policy "Users can vote once"
on public.votes for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Anyone can view settings" on public.vote_settings;
create policy "Anyone can view settings"
on public.vote_settings for select using (true);

drop policy if exists "Admins can update settings" on public.vote_settings;
create policy "Admins can update settings"
on public.vote_settings for update to authenticated
using ((auth.jwt() ->> 'email') = any (array['sj10225@dge.go.kr']))
with check ((auth.jwt() ->> 'email') = any (array['sj10225@dge.go.kr']));

insert into public.candidates (name, description)
select * from (values
  ('후보 A', '첫 번째 후보입니다.'),
  ('후보 B', '두 번째 후보입니다.'),
  ('후보 C', '세 번째 후보입니다.')
) as x(name, description)
where not exists (select 1 from public.candidates);
