-- VOTE database
-- Supabase SQL Editor에서 전체 실행하세요.

create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  created_at timestamptz default now()
);

create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  created_at timestamptz default now(),
  constraint one_vote_per_user unique (user_id)
);

alter table public.candidates enable row level security;
alter table public.votes enable row level security;

drop policy if exists "Anyone can view candidates" on public.candidates;
create policy "Anyone can view candidates"
on public.candidates
for select
using (true);

drop policy if exists "Users can view own vote" on public.votes;
create policy "Users can view own vote"
on public.votes
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can vote once" on public.votes;
create policy "Users can vote once"
on public.votes
for insert
to authenticated
with check (auth.uid() = user_id);

-- 테스트용 후보
insert into public.candidates (name, description)
select * from (values
  ('후보 A', '첫 번째 후보입니다.'),
  ('후보 B', '두 번째 후보입니다.'),
  ('후보 C', '세 번째 후보입니다.')
) as x(name, description)
where not exists (select 1 from public.candidates);
